COLUMNAS_BITACORA = [
    "g_fecha", "g_tecnico", "g_cantidadEquipos",
    "g_numeroRemisionEquipos", "g_numeroRemisionEquiposSalida",
    "g_liberaRepuestos", "g_numeroRemisionRepuestos",
    "g_mostrarAlistamiento", "g_mostrarMantenimiento",
    "g_mostrarTercero", "g_ayudaOtroTecnico", "g_nombreOtroTecnico",
    "a_alarmaCero", "a_flujoMaximo", "a_desconexion",
    "a_marcaCalor", "a_cantidadMarcaCalor", "a_i_equiposVerificados",
    "a_i_horaInicio", "a_i_horaFin", "a_i_equiposApoyo",
    "a_l_equiposVerificados", "a_l_horaInicio", "a_l_horaFin",
    "a_l_equiposApoyo", "a_p_equiposVerificados", "a_p_horaInicio",
    "a_p_horaFin", "a_p_equiposApoyo", "a_li_equiposVerificados",
    "a_li_horaInicio", "a_li_horaFin", "a_li_equiposApoyo",
    "m_realizaReparacion", "m_s_equiposVerificados", "m_s_horaInicio",
    "m_s_horaFin", "m_s_equiposApoyo", "m_i_equiposVerificados",
    "m_i_horaInicio", "m_i_horaFin", "m_i_equiposApoyo",
    "m_l_equiposVerificados", "m_l_horaInicio", "m_l_horaFin",
    "m_l_equiposApoyo", "m_p_equiposVerificados", "m_p_horaInicio",
    "m_p_horaFin", "m_p_equiposApoyo", "m_r_equiposIngresados",
    "m_r_equiposReparados", "m_r_horaInicio", "m_r_horaFin",
    "m_r_equiposApoyo", "m_li_equiposLiberados", "m_li_horaInicio",
    "m_li_horaFin", "m_li_equiposApoyo", "m_te_equiposVerificados",
    "m_te_horaInicio", "m_te_horaFin", "t_s_equiposVerificados",
    "t_s_horaInicio", "t_s_horaFin", "t_s_equiposApoyo",
    "t_i_equiposVerificados", "t_i_horaInicio", "t_i_horaFin",
    "t_i_equiposApoyo", "t_l_equiposVerificados", "t_l_horaInicio",
    "t_l_horaFin", "t_l_equiposApoyo", "t_p_equiposVerificados",
    "t_p_horaInicio", "t_p_horaFin", "t_p_equiposApoyo",
    "t_li_equiposLiberados", "t_li_horaInicio", "t_li_horaFin",
    "t_li_equiposApoyo", "t_te_equiposVerificados", "t_te_horaInicio",
    "t_te_horaFin"
]
